backend:
  name: github
  repo: bglatman/rsn_website
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Posts"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Source", name: "source", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false}
      - {label: "Show in Carousel", name: "carousel", widget: "boolean", required: false}
  - name: "ads"
    label: "Ads"
    files:
      - file: "src/pages/backgroundAd/index.md"
        label: "Background"
        name: "background"
        fields: 
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "backgroundAd"}
          - {label: "Category", name: "category", widget: "hidden", default: "ad"}
          - {label: "Title", name: "title", widget: "hidden", default: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "SEO Alt description", name: "alt", widget: "string"}
      - file: "src/pages/headerAd/index.md"
        label: "Header"
        name: "header"
        fields: 
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "headerAd"}
          - {label: "Category", name: "category", widget: "hidden", default: "ad"}
          - {label: "Title", name: "title", widget: "hidden", default: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "SEO Alt description", name: "alt", widget: "string"}
      - file: "src/pages/sideAd/index.md"
        label: "Side Ad"
        name: "side"
        fields: 
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "sideAd"}
          - {label: "Category", name: "category", widget: "hidden", default: "ad"}
          - {label: "Title", name: "title", widget: "hidden", default: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "SEO Alt description", name: "alt", widget: "string"}